<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c3d8728f-cd64-4b97-b966-243dae5f5dcb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="contentstack.csharp" Version="2.25.2" />
  </ItemGroup>

</Project>
